import type { GraphData } from './types';

export const graphData: GraphData = {
  nodes: [
    { id: 'client', label: 'Client App', category: 'user', description: 'Web/mobile frontend consuming the API', connections: 3 },
    { id: 'gateway', label: 'API Gateway', category: 'core', description: 'Entry point — handles routing, auth, rate limiting', connections: 6 },
    { id: 'auth', label: 'Auth Service', category: 'service', description: 'JWT issuance, token validation, session management', connections: 4 },
    { id: 'users', label: 'User Service', category: 'service', description: 'User CRUD, profile management, preferences', connections: 4 },
    { id: 'orders', label: 'Order Service', category: 'service', description: 'Order lifecycle, cart, checkout flow', connections: 5 },
    { id: 'payments', label: 'Payment Service', category: 'service', description: 'Stripe integration, billing, refunds', connections: 4 },
    { id: 'notify', label: 'Notification Hub', category: 'service', description: 'Email, SMS, push — fan-out to multiple channels', connections: 3 },
    { id: 'search', label: 'Search Engine', category: 'service', description: 'Elasticsearch-backed product & content search', connections: 2 },
    { id: 'cdn', label: 'CDN / Assets', category: 'external', description: 'Static assets, images, global edge caching', connections: 2 },
    { id: 'userdb', label: 'Users DB', category: 'database', description: 'PostgreSQL — user accounts and profiles', connections: 2 },
    { id: 'orderdb', label: 'Orders DB', category: 'database', description: 'PostgreSQL — orders, line items, history', connections: 2 },
    { id: 'cache', label: 'Redis Cache', category: 'database', description: 'Session tokens, rate-limit counters, hot data', connections: 3 },
    { id: 'queue', label: 'Message Queue', category: 'core', description: 'RabbitMQ — async event bus between services', connections: 4 },
    { id: 'stripe', label: 'Stripe API', category: 'external', description: 'Third-party payment processor', connections: 1 },
    { id: 'sendgrid', label: 'SendGrid', category: 'external', description: 'Transactional email delivery', connections: 1 },
  ],
  edges: [
    { id: 'e1',  source: 'client',   target: 'gateway',  label: 'HTTPS', weight: 3 },
    { id: 'e2',  source: 'client',   target: 'cdn',      label: 'assets', weight: 2 },
    { id: 'e3',  source: 'gateway',  target: 'auth',     label: 'verify', weight: 2 },
    { id: 'e4',  source: 'gateway',  target: 'users',    label: 'REST', weight: 2 },
    { id: 'e5',  source: 'gateway',  target: 'orders',   label: 'REST', weight: 2 },
    { id: 'e6',  source: 'gateway',  target: 'search',   label: 'REST', weight: 1 },
    { id: 'e7',  source: 'auth',     target: 'cache',    label: 'sessions', weight: 2 },
    { id: 'e8',  source: 'auth',     target: 'userdb',   label: 'lookup', weight: 2 },
    { id: 'e9',  source: 'users',    target: 'userdb',   label: 'R/W', weight: 3 },
    { id: 'e10', source: 'users',    target: 'cache',    label: 'cache', weight: 1 },
    { id: 'e11', source: 'orders',   target: 'orderdb',  label: 'R/W', weight: 3 },
    { id: 'e12', source: 'orders',   target: 'payments', label: 'charge', weight: 2 },
    { id: 'e13', source: 'orders',   target: 'queue',    label: 'events', weight: 2 },
    { id: 'e14', source: 'payments', target: 'stripe',   label: 'API', weight: 2 },
    { id: 'e15', source: 'payments', target: 'queue',    label: 'paid', weight: 1 },
    { id: 'e16', source: 'queue',    target: 'notify',   label: 'trigger', weight: 2 },
    { id: 'e17', source: 'notify',   target: 'sendgrid', label: 'email', weight: 2 },
    { id: 'e18', source: 'cdn',      target: 'cache',    label: 'invalidate', weight: 1 },
  ],
};
